#!/usr/bin/env python3

import argparse
from src.Remote.adversary_client import AdversaryClient

if __name__ == '__main__':
	# Create the command line parser
	parser = argparse.ArgumentParser(allow_abbrev=False)
	parser.add_argument("--address", type=str,
						help="IP address to connect to", default='127.0.0.1')
	parser.add_argument("--port", type=int, help="Port number to connect to",
						default=45678)
	args = parser.parse_args()

	c = AdversaryClient(args.address, args.port)
	c.run()


	


